/**
 * resolve-spotify.ts
 *
 * Re-resolves every example track in src/data/genres.ts to a real Spotify track
 * ID using the official Spotify Web API, and writes src/data/spotifyIds.ts (the
 * map the app ships with), keyed by genre id and aligned to each genre's
 * `examples` order.
 *
 * Prereqs:
 *   - Node 18+ (global fetch). Node 23.6+ runs this .ts file directly; on older
 *     Node use `npx tsx scripts/resolve-spotify.ts`.
 *   - A Spotify app (https://developer.spotify.com/dashboard) with
 *     SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET set in your environment.
 *
 * Run:
 *   SPOTIFY_CLIENT_ID=xxx SPOTIFY_CLIENT_SECRET=yyy node scripts/resolve-spotify.ts
 *
 * Uses the Client Credentials flow (no user login). Tracks that don't resolve are
 * left null and listed at the end for manual review — don't hand-guess IDs.
 */

import { writeFileSync } from "node:fs";
import { GENRES } from "../src/data/genres.ts";

const CLIENT_ID = process.env.SPOTIFY_CLIENT_ID;
const CLIENT_SECRET = process.env.SPOTIFY_CLIENT_SECRET;

if (!CLIENT_ID || !CLIENT_SECRET) {
  console.error("Set SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET before running.");
  process.exit(1);
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function getToken(): Promise<string> {
  const creds = Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`).toString("base64");
  const res = await fetch("https://accounts.spotify.com/api/token", {
    method: "POST",
    headers: {
      Authorization: `Basic ${creds}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: "grant_type=client_credentials",
  });
  if (!res.ok) throw new Error(`Token request failed: ${res.status}`);
  const data = (await res.json()) as { access_token: string };
  return data.access_token;
}

async function searchTrack(
  token: string,
  artist: string,
  title: string,
): Promise<string | null> {
  const q = encodeURIComponent(`track:"${title}" artist:"${artist}"`);
  const url = `https://api.spotify.com/v1/search?q=${q}&type=track&limit=1`;
  const res = await fetch(url, { headers: { Authorization: `Bearer ${token}` } });

  if (res.status === 429) {
    const retry = Number(res.headers.get("Retry-After") ?? "1");
    await sleep((retry + 1) * 1000);
    return searchTrack(token, artist, title);
  }
  if (!res.ok) {
    console.warn(`Search failed (${res.status}) for ${artist} - ${title}`);
    return null;
  }

  const data = (await res.json()) as {
    tracks?: { items?: Array<{ id: string }> };
  };
  return data?.tracks?.items?.[0]?.id ?? null;
}

async function main() {
  const token = await getToken();
  const map: Record<string, (string | null)[]> = {};
  const misses: string[] = [];

  for (const genre of GENRES) {
    const ids: (string | null)[] = [];
    for (const ex of genre.examples) {
      const id = await searchTrack(token, ex.artist, ex.title);
      if (!id) misses.push(`${genre.name}: ${ex.artist} - ${ex.title}`);
      ids.push(id);
      await sleep(120); // stay well under the rate limit
    }
    map[genre.id] = ids;
    console.log(`Resolved ${genre.name}`);
  }

  const body =
    `/* Generated by scripts/resolve-spotify.ts — do not edit by hand. */\n\n` +
    `export const SPOTIFY_IDS: Record<string, (string | null)[]> = ${JSON.stringify(
      map,
      null,
      2,
    )};\n`;
  writeFileSync(new URL("../src/data/spotifyIds.ts", import.meta.url), body);

  console.log(`\nWrote src/data/spotifyIds.ts (${Object.keys(map).length} genres).`);
  if (misses.length) {
    console.log(`\n${misses.length} tracks need manual review:`);
    misses.forEach((m) => console.log("  - " + m));
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
