/* Generated by scripts/resolve-artists-spotify.ts — do not edit by hand. */

export type SpotifyArtistData = {
  genres: string[];
  spotifyArtistId?: string;
  tracks: { title: string; spotifyId: string }[];
};

export const ARTIST_SPOTIFY: Record<string, SpotifyArtistData> = {
  "calvin-harris": {
    "genres": [],
    "spotifyArtistId": "7CajNmpbOovFoOoasH2HaY",
    "tracks": [
      {
        "title": "Feel So Close",
        "spotifyId": "1gihuPhrLraKYrJMAEONyc"
      },
      {
        "title": "Summer",
        "spotifyId": "6YUTL4dYpB9xZO5qExPf05"
      },
      {
        "title": "Sweet Nothing",
        "spotifyId": "24LS4lQShWyixJ0ZrJXfJ5"
      },
      {
        "title": "This Is What You Came For",
        "spotifyId": "2vlDrKpOC0eSTqTDRcbYyw"
      },
      {
        "title": "One Kiss",
        "spotifyId": "7ef4DlsgrMEH11cDZd32M6"
      }
    ]
  },
  "david-guetta": {
    "genres": [],
    "spotifyArtistId": "1Cs0zKBU1kc0i8ypK3B9ai",
    "tracks": [
      {
        "title": "When Love Takes Over",
        "spotifyId": "77FULy278MulVvGWS8BfK7"
      },
      {
        "title": "Titanium",
        "spotifyId": "0lHAMNU8RGiIObScrsRgmP"
      },
      {
        "title": "Memories",
        "spotifyId": "5p3SJ3CYqrmFbboAtfNo5n"
      },
      {
        "title": "Hey Mama",
        "spotifyId": "5b2bu6yyATC1zMXDGScJ2d"
      },
      {
        "title": "I'm Good (Blue)",
        "spotifyId": "4uUG5RXrOk84mYEfFvj3cK"
      }
    ]
  },
  "daft-punk": {
    "genres": [],
    "spotifyArtistId": "4tZwfgrHOc3mvqYlEYSvVi",
    "tracks": [
      {
        "title": "One More Time",
        "spotifyId": "0DiWol3AO6WpXZgp0goxAV"
      },
      {
        "title": "Around the World",
        "spotifyId": "1pKYYY0dkg23sQQXi0Q5zN"
      },
      {
        "title": "Harder, Better, Faster, Stronger",
        "spotifyId": "5W3cjX2J3tjhG8zb6u0qHn"
      },
      {
        "title": "Da Funk",
        "spotifyId": "0MyY4WcN7DIfbSmp5yej5z"
      },
      {
        "title": "Get Lucky",
        "spotifyId": "69kOkLUCkxIZYexIgSG8rq"
      }
    ]
  },
  "deadmau5": {
    "genres": [],
    "spotifyArtistId": "2CIMQHirSU0MQqyYHq0eOx",
    "tracks": [
      {
        "title": "Strobe",
        "spotifyId": "5vTPFJOzgr6IzF11Kvjzls"
      },
      {
        "title": "Ghosts 'n' Stuff",
        "spotifyId": "0FZ8ULT8WR1xwCIzjVRxnw"
      },
      {
        "title": "I Remember",
        "spotifyId": "5miifYL53idUsDxGKjICtb"
      },
      {
        "title": "The Veldt",
        "spotifyId": "4ezalcKN0KnYuZiEw2jFgc"
      },
      {
        "title": "Some Chords",
        "spotifyId": "535PzroKb08Y1h8mRdHoYC"
      }
    ]
  },
  "eric-prydz": {
    "genres": [],
    "spotifyArtistId": "5sm0jQ1mq0dusiLtDJ2b4R",
    "tracks": [
      {
        "title": "Opus",
        "spotifyId": "3v2oAQomhOcYCPPHafS3KV"
      },
      {
        "title": "Call on Me",
        "spotifyId": "1xNcBAoUw8Hz6LqK2jt4Ff"
      },
      {
        "title": "Pjanoo",
        "spotifyId": "0EzVcavTFL5YEj0945ifIi"
      },
      {
        "title": "Generate",
        "spotifyId": "4Dg0FSovv3n8IBS9QMezTp"
      },
      {
        "title": "Every Day",
        "spotifyId": "4j1hJwuawbvpm2q2orbgj7"
      }
    ]
  },
  "avicii": {
    "genres": [],
    "spotifyArtistId": "1vCWHaC5f2uS3yhpwWbIA6",
    "tracks": [
      {
        "title": "Levels",
        "spotifyId": "5UqCQaDshqbIk3pkhy4Pjg"
      },
      {
        "title": "Wake Me Up",
        "spotifyId": "0nrRP2bk19rLc0orkWPQk2"
      },
      {
        "title": "Hey Brother",
        "spotifyId": "4lhqb6JvbHId48OUJGwymk"
      },
      {
        "title": "Waiting for Love",
        "spotifyId": "2P4OICZRVAQcYAV2JReRfj"
      },
      {
        "title": "The Nights",
        "spotifyId": "0ct6r3EGTcMLPtrXHDvVjc"
      }
    ]
  },
  "swedish-house-mafia": {
    "genres": [],
    "spotifyArtistId": "1h6Cn3P4NGzXbaXidqURXs",
    "tracks": [
      {
        "title": "Don't You Worry Child",
        "spotifyId": "2V65y3PX4DkRhy1djlxd9p"
      },
      {
        "title": "One (Your Name)",
        "spotifyId": "5EJcVJZBl6HTfSf6z4dC78"
      },
      {
        "title": "Greyhound",
        "spotifyId": "0VffaI2jwQknRrxpECYHsF"
      },
      {
        "title": "Save the World",
        "spotifyId": "65hRZOQkVjmBdusz1N7aOv"
      },
      {
        "title": "Don't You Worry Child",
        "spotifyId": "2V65y3PX4DkRhy1djlxd9p"
      }
    ]
  },
  "axwell-ingrosso": {
    "genres": [],
    "tracks": [
      {
        "title": "Something New",
        "spotifyId": "5C4NMi4fPpdFPnMZVsyG8H"
      },
      {
        "title": "More Than You Know",
        "spotifyId": "6h5PAsRni4IRlxWr6uDPTP"
      },
      {
        "title": "Sun Is Shining",
        "spotifyId": "4b2tcjrG1qUkSdsqEFP2dB"
      },
      {
        "title": "On My Way",
        "spotifyId": "5zATs59c3mikRxLK6ODE0p"
      }
    ]
  },
  "alesso": {
    "genres": [],
    "spotifyArtistId": "4AVFqumd2ogHFlRbKIjp1t",
    "tracks": [
      {
        "title": "Heroes (We Could Be)",
        "spotifyId": "3zU9rdflI65tK4dkkNSp77"
      },
      {
        "title": "Years",
        "spotifyId": "5pVk15sR3OgIeKBKqG9jWw"
      },
      {
        "title": "Calling (Lose My Mind)",
        "spotifyId": "6LNjIsgHNs4q75uPt4rYf6"
      },
      {
        "title": "If I Lose Myself (Alesso Remix)",
        "spotifyId": "1hZk9dktp4yRFTm0TrycuH"
      }
    ]
  },
  "martin-garrix": {
    "genres": [],
    "spotifyArtistId": "60d24wfXkVzDSfLS6hyCjZ",
    "tracks": [
      {
        "title": "Animals",
        "spotifyId": "0A9mHc7oYUoCECqByV8cQR"
      },
      {
        "title": "Scared to Be Lonely",
        "spotifyId": "3ebXMykcMXOcLeJ9xZ17XH"
      },
      {
        "title": "In the Name of Love",
        "spotifyId": "23L5CiUhw2jV1OIMwthR3S"
      },
      {
        "title": "Tremor",
        "spotifyId": "0gpvO8fKvZcQ4u54rdu469"
      }
    ]
  },
  "hardwell": {
    "genres": [],
    "spotifyArtistId": "6BrvowZBreEkXzJQMpL174",
    "tracks": [
      {
        "title": "Spaceman",
        "spotifyId": "0T64SYe5jQTQq57E6d94N3"
      },
      {
        "title": "Apollo",
        "spotifyId": "7EdxI2Yro4AW2HH3akwqms"
      },
      {
        "title": "Everybody Is in the Place",
        "spotifyId": "2pc8FSxMukUM6jA2bbM9oz"
      }
    ]
  },
  "dimitri-vegas-like-mike": {
    "genres": [],
    "spotifyArtistId": "73jBynjsVtofjRpdpRAJGk",
    "tracks": [
      {
        "title": "Tremor",
        "spotifyId": "0gpvO8fKvZcQ4u54rdu469"
      },
      {
        "title": "The Hum",
        "spotifyId": "0h1yorZXMX1sRRLfq0aOAK"
      },
      {
        "title": "Mammoth",
        "spotifyId": "0KNYrJlQoXIUMatEyuwFlU"
      }
    ]
  },
  "afrojack": {
    "genres": [],
    "spotifyArtistId": "4D75GcNG95ebPtNvoNVXhz",
    "tracks": [
      {
        "title": "Take Over Control",
        "spotifyId": "4iD3msRl5hJUBEtrQwnR4k"
      },
      {
        "title": "Ten Feet Tall",
        "spotifyId": "2ldAdghnrO34HPcZ0IWfTu"
      },
      {
        "title": "The Spark",
        "spotifyId": "5CYJB5Md92kvcrZ4lJDALY"
      }
    ]
  },
  "steve-aoki": {
    "genres": [],
    "spotifyArtistId": "77AiFEVeAVj2ORpC85QVJs",
    "tracks": [
      {
        "title": "Pursuit of Happiness (Remix)",
        "spotifyId": "5PX4uS1LqlWEPL69phPVQQ"
      },
      {
        "title": "Boneless",
        "spotifyId": "75f4fO9adbAYJqNBKJNrxs"
      },
      {
        "title": "Just Hold On",
        "spotifyId": "3EmmCZoqpWOTY1g2GBwJoR"
      }
    ]
  },
  "zedd": {
    "genres": [],
    "spotifyArtistId": "2qxJFvFYMEDqd7ui6kSAcq",
    "tracks": [
      {
        "title": "Clarity",
        "spotifyId": "60wwxj6Dd9NJlirf84wr2c"
      },
      {
        "title": "Stay",
        "spotifyId": "2QtJA4gbwe1AcanB2p21aP"
      },
      {
        "title": "The Middle",
        "spotifyId": "09IStsImFySgyp0pIQdqAc"
      },
      {
        "title": "Spectrum",
        "spotifyId": "1dFkD1JfRMzwO6hwUsE8aS"
      }
    ]
  },
  "kygo": {
    "genres": [],
    "spotifyArtistId": "23fqKkggKUBHNkbKtXEls4",
    "tracks": [
      {
        "title": "Firestone",
        "spotifyId": "1I8tHoNBFTuoJAlh4hfVVE"
      },
      {
        "title": "Stole the Show",
        "spotifyId": "5masKPHeAOVNgxdLebIcK7"
      },
      {
        "title": "It Ain't Me",
        "spotifyId": "12GEpg2XOPyqk03JZEZnJs"
      },
      {
        "title": "Stargazing",
        "spotifyId": "0Zbbxnx4SGGHoIow4PpISP"
      }
    ]
  },
  "robin-schulz": {
    "genres": [],
    "spotifyArtistId": "3t5xRXzsuZmMDkQzgOX35S",
    "tracks": [
      {
        "title": "Prayer in C (Robin Schulz Remix)",
        "spotifyId": "3k9FFXVPn3ua8dlpkxlCvZ"
      },
      {
        "title": "Sugar",
        "spotifyId": "5tf1VVWniHgryyumXyJM7w"
      },
      {
        "title": "Sun Goes Down",
        "spotifyId": "4zLBcDtvYNVtF9fnG6lme3"
      }
    ]
  },
  "tiesto": {
    "genres": [],
    "spotifyArtistId": "2o5jDhtHVPhrJdv3cEQ99Z",
    "tracks": [
      {
        "title": "Adagio for Strings",
        "spotifyId": "76uTbKqlADkTPQ1bXHMBww"
      },
      {
        "title": "Red Lights",
        "spotifyId": "5L2l7mI8J1USMzhsmdjat9"
      },
      {
        "title": "The Business",
        "spotifyId": "57uNXnf4ciHYP4HktbIbzC"
      },
      {
        "title": "Secrets",
        "spotifyId": "0NIC4unbe5KZOp1d9T7OaF"
      },
      {
        "title": "Wow",
        "spotifyId": "3qPXWPkEZgUhUgPifbE99z"
      }
    ]
  },
  "fisher": {
    "genres": [],
    "spotifyArtistId": "1VJ0briNOlXRtJUAzoUJdt",
    "tracks": [
      {
        "title": "Losing It",
        "spotifyId": "6ho0GyrWZN3mhi9zVRW7xi"
      },
      {
        "title": "You Little Beauty",
        "spotifyId": "1gRQxbfL4ULWyTosgXSbWT"
      },
      {
        "title": "Stop It",
        "spotifyId": "627JZ3dVd88Xc5IoHOeNT5"
      },
      {
        "title": "Just Feels Tight",
        "spotifyId": "4jbg2o0TehLjOlddOxHJTO"
      }
    ]
  },
  "chris-lake": {
    "genres": [],
    "spotifyArtistId": "5Igpc9iLZ3YGtKeYfSrrOE",
    "tracks": [
      {
        "title": "Turn Off the Lights",
        "spotifyId": "42CMeHqi0S8sbKvrzLyixS"
      },
      {
        "title": "Operator (Ring Ring)",
        "spotifyId": "4oXT61OL4mDPRXbjq2d7b1"
      },
      {
        "title": "Free Your Body",
        "spotifyId": "7DdWzRlhzOToeHdOYbBt8z"
      },
      {
        "title": "I Want You",
        "spotifyId": "7IM73yy9leN8ftZsOVmVTO"
      }
    ]
  },
  "john-summit": {
    "genres": [],
    "spotifyArtistId": "7kNqXtgeIwFtelmRjWv205",
    "tracks": [
      {
        "title": "Deep End",
        "spotifyId": "7JdiXX87BugXUDhQ89GEc8"
      },
      {
        "title": "La Danza",
        "spotifyId": "6KNlhaeBrlHUsVItPrpkyn"
      },
      {
        "title": "Where You Are",
        "spotifyId": "3pUz2qJe5nqZemi3hhIxMk"
      },
      {
        "title": "Light Years",
        "spotifyId": "2wRKES8HKm4EutRHz7JD1x"
      }
    ]
  },
  "dom-dolla": {
    "genres": [],
    "spotifyArtistId": "205i7E8fNVfojowcQSfK9m",
    "tracks": [
      {
        "title": "San Frandisco",
        "spotifyId": "3T00mhdOYUuM5yiuPs3xhs"
      },
      {
        "title": "Take It",
        "spotifyId": "14fIlfcmFPlj4V2IazeJ25"
      },
      {
        "title": "Miracle Maker",
        "spotifyId": "6txvQu0zUbiqG24A8XMLnK"
      },
      {
        "title": "Pump the Brakes",
        "spotifyId": "1Gz2E1chOzRyhFXHJYWw8y"
      }
    ]
  },
  "fred-again": {
    "genres": [],
    "spotifyArtistId": "4oLeXFyACqeem2VImYeBFe",
    "tracks": [
      {
        "title": "Delilah (pull me out of this)",
        "spotifyId": "5w9upngVRHNjdZcRC7Xxr2"
      },
      {
        "title": "Marea (we've lost dancing)",
        "spotifyId": "5Z8Dj3LtbyCMiwE86rhg2f"
      },
      {
        "title": "Rumble",
        "spotifyId": "74fmYjFwt9CqEFAh8ybeBD"
      },
      {
        "title": "Turn On the Lights again.. (with Future)",
        "spotifyId": "4ptnQ0kQnN1U1Ig8TSslj6"
      }
    ]
  },
  "disclosure": {
    "genres": [],
    "spotifyArtistId": "6nS5roXSAGhTGr34W6n7Et",
    "tracks": [
      {
        "title": "Latch",
        "spotifyId": "51ODNNDZm21HU7wI7cccRr"
      },
      {
        "title": "White Noise",
        "spotifyId": "5EWFuo4ObEnfndc57sTuIo"
      },
      {
        "title": "You & Me (Flume Remix)",
        "spotifyId": "3W2ZcrRsInZbjWylOi6KhZ"
      },
      {
        "title": "When a Fire Starts to Burn",
        "spotifyId": "7qVLZuvzNjyiy3TVtEBwBE"
      }
    ]
  },
  "duke-dumont": {
    "genres": [],
    "spotifyArtistId": "61lyPtntblHJvA7FMMhi7E",
    "tracks": [
      {
        "title": "Need U (100%)",
        "spotifyId": "1I0mRrowc6HCoED6hoAB2q"
      },
      {
        "title": "I Got U",
        "spotifyId": "69gQgkobVW8bWjoCjBYQUd"
      },
      {
        "title": "Ocean Drive",
        "spotifyId": "4b93D55xv3YCH5mT4p6HPn"
      }
    ]
  },
  "gorgon-city": {
    "genres": [],
    "spotifyArtistId": "4VNQWV2y1E97Eqo2D5UTjx",
    "tracks": [
      {
        "title": "Ready for Your Love",
        "spotifyId": "5wGLQvq6JoxYZX7V3ymPS5"
      },
      {
        "title": "Real",
        "spotifyId": "6jz9EMWHffNKVlZQVXOLoz"
      },
      {
        "title": "Imagination",
        "spotifyId": "2VGTe5PkHOlZuayLYDjtb1"
      }
    ]
  },
  "mk": {
    "genres": [],
    "spotifyArtistId": "099tHc1nWooG9wPtUYX9Mi",
    "tracks": [
      {
        "title": "17",
        "spotifyId": "15DwFznkBJir7AK9PyMyRR"
      },
      {
        "title": "Back & Forth",
        "spotifyId": "4M8x1TR36VMQMFMbGCdoyA"
      },
      {
        "title": "Dior",
        "spotifyId": "3kPNkracUxYvwpzkdpHMQQ"
      }
    ]
  },
  "camelphat": {
    "genres": [],
    "spotifyArtistId": "240wlM8vDrf6S4zCyzGj2W",
    "tracks": [
      {
        "title": "Cola",
        "spotifyId": "0aL5jEWqfIwNDB3tdzyzH4"
      },
      {
        "title": "Panic Room",
        "spotifyId": "3MkuFR7t25mu7Iscp6GGiV"
      },
      {
        "title": "Breathe",
        "spotifyId": "6TR0FGw4zhlGbQALN065AI"
      }
    ]
  },
  "meduza": {
    "genres": [],
    "spotifyArtistId": "0xRXCcSX89eobfrshSVdyu",
    "tracks": [
      {
        "title": "Piece of Your Heart",
        "spotifyId": "5RDUCbvwPZdmjFbhZ5EY4N"
      },
      {
        "title": "Lose Control",
        "spotifyId": "2unqiEdHtabnsbv6TJ7gCW"
      },
      {
        "title": "Paradise",
        "spotifyId": "40FUdLENDY3sZmHEM25lpE"
      }
    ]
  },
  "purple-disco-machine": {
    "genres": [],
    "spotifyArtistId": "2WBJQGf1bT1kxuoqziH5g4",
    "tracks": [
      {
        "title": "Hypnotized",
        "spotifyId": "7HxWZggiHyGWT9ZSmWzcxu"
      },
      {
        "title": "Fireworks",
        "spotifyId": "154YAkNQuFHLV3LbP7gP1f"
      },
      {
        "title": "In the Dark",
        "spotifyId": "0k5RQGviUoEt78mfqI3wDV"
      }
    ]
  },
  "acraze": {
    "genres": [],
    "spotifyArtistId": "4pnp4w9g30yLfVIAFnZMRd",
    "tracks": [
      {
        "title": "Do It To It",
        "spotifyId": "7cyGxmLnHWlwt41cr2RZzG"
      },
      {
        "title": "Believe",
        "spotifyId": "6h5y2LCqCQudsCarn61CNE"
      }
    ]
  },
  "vintage-culture": {
    "genres": [],
    "spotifyArtistId": "28uJnu5EsrGml2tBd7y8ts",
    "tracks": [
      {
        "title": "Weak",
        "spotifyId": "37uMiu52DbSIx3SJ3sGDow"
      },
      {
        "title": "It Is What It Is",
        "spotifyId": "6CjRrRsQpJijQsMnCUAWrs"
      },
      {
        "title": "Commotion",
        "spotifyId": "2qf9Ad1hgLF5oM9SdMJdDU"
      }
    ]
  },
  "black-coffee": {
    "genres": [],
    "spotifyArtistId": "6wMr4zKPrrR0UVz08WtUWc",
    "tracks": [
      {
        "title": "Drive",
        "spotifyId": "5cOJ2APoxJfaGjEC7CYc0K"
      },
      {
        "title": "SBCNCSLY",
        "spotifyId": "3CP1ehiVZEOl7IZ6dORXuS"
      },
      {
        "title": "We Dance Again",
        "spotifyId": "6HvCOJvbEzVTmEFmv79pTf"
      }
    ]
  },
  "lane-8": {
    "genres": [],
    "spotifyArtistId": "27gtK7m9vYwCyJ04zz0kIb",
    "tracks": [
      {
        "title": "Brightest Lights",
        "spotifyId": "49jWS1fz7QZQa4mBIqB0mu"
      },
      {
        "title": "Atlas",
        "spotifyId": "6YFRyll4isFUJrbHSeM1oJ"
      },
      {
        "title": "Road",
        "spotifyId": "6kckNpuM5oXZrObLExRg6d"
      }
    ]
  },
  "ben-bohmer": {
    "genres": [],
    "spotifyArtistId": "5tDjiBYUsTqzd0RkTZxK7u",
    "tracks": [
      {
        "title": "After Earth",
        "spotifyId": "6mjN72fXeZwLkCDG7rHH3N"
      },
      {
        "title": "Breathing",
        "spotifyId": "1MvLmHeLkaNgUScgbUVnWJ"
      },
      {
        "title": "Beautiful Lies",
        "spotifyId": "58ney0bG2Vwecj8QzNGRkV"
      }
    ]
  },
  "anyma": {
    "genres": [],
    "spotifyArtistId": "4iBwchw0U0GZv5RfVYSMxN",
    "tracks": [
      {
        "title": "Eternity",
        "spotifyId": "1GBBbKOarAJ38HwIfLcOji"
      },
      {
        "title": "Consciousness",
        "spotifyId": "1pM05FAgX2lLp3NwpMY2vs"
      },
      {
        "title": "Genesys",
        "spotifyId": "5WJhBV5ZHOWaRtZwnfYurJ"
      }
    ]
  },
  "tale-of-us": {
    "genres": [],
    "spotifyArtistId": "1UL813H5aj3e8ekE5RqWqc",
    "tracks": [
      {
        "title": "Nova",
        "spotifyId": "1HiyVDI0InKvPJ8DeNe8Wz"
      },
      {
        "title": "Time",
        "spotifyId": "4d2Gndzn9dnmUC8jIzI9d4"
      },
      {
        "title": "Dark Song",
        "spotifyId": "4O2xx1GL1WIhqZIwIJauPY"
      }
    ]
  },
  "artbat": {
    "genres": [],
    "spotifyArtistId": "3BkRu2TGd2I1uBxZKddfg1",
    "tracks": [
      {
        "title": "Element",
        "spotifyId": "2gPFGrisUrWpKZHycEJp1s"
      },
      {
        "title": "Horizon",
        "spotifyId": "7Mqdzo9NcZLUwTAoyV2AeE"
      },
      {
        "title": "Coronita",
        "spotifyId": "58caScGqKTQIDDJQ7QnJU8"
      }
    ]
  },
  "boris-brejcha": {
    "genres": [],
    "spotifyArtistId": "6caPJFLv1wesmM7gwK1ACy",
    "tracks": [
      {
        "title": "Gravity",
        "spotifyId": "30WnQsvwFeYEd9k08vV7Dl"
      },
      {
        "title": "Purple Noise",
        "spotifyId": "6MoTeX5dtuPZ3hwaecuBkz"
      },
      {
        "title": "Happiness",
        "spotifyId": "3CPEi77tTjJDlUgZKXpoOl"
      }
    ]
  },
  "tchami": {
    "genres": [],
    "spotifyArtistId": "1KpCi9BOfviCVhmpI4G2sY",
    "tracks": [
      {
        "title": "After Life",
        "spotifyId": "3dhPpCQvw3kn7so6mkTbJ3"
      },
      {
        "title": "Promesses",
        "spotifyId": "4Vkvji54GIGgL9e2cxRlP9"
      },
      {
        "title": "Adieu",
        "spotifyId": "53Us5C3wTQ2zi6ODWhmHMN"
      },
      {
        "title": "Proud",
        "spotifyId": "5bTjXhNv9Cu5ZWVjxUHVGE"
      }
    ]
  },
  "oliver-heldens": {
    "genres": [],
    "spotifyArtistId": "5nki7yRhxgM509M5ADlN1p",
    "tracks": [
      {
        "title": "Gecko (Overdrive)",
        "spotifyId": "483XiZ5o13Cc1zoWV7jGml"
      },
      {
        "title": "Koala",
        "spotifyId": "2LsKvF1f5PVm18UZgQrwml"
      },
      {
        "title": "Last All Night (Koala)",
        "spotifyId": "4aFuYIAI1hNXVP1K2CAMbM"
      }
    ]
  },
  "don-diablo": {
    "genres": [],
    "spotifyArtistId": "1l2ekx5skC4gJH8djERwh1",
    "tracks": [
      {
        "title": "On My Mind",
        "spotifyId": "40dweDLovf20EbZCq1Kwj1"
      },
      {
        "title": "Survive",
        "spotifyId": "1gnKUue6F9gXXHQshCBwEs"
      },
      {
        "title": "Universe",
        "spotifyId": "21XOKNYyj4DhDdhAUWhI1W"
      }
    ]
  },
  "jauz": {
    "genres": [],
    "spotifyArtistId": "5ttgIeUVka6FLyi00Uu5h8",
    "tracks": [
      {
        "title": "Feel the Volume",
        "spotifyId": "03IxJiB8ZOH9hEQZF5mCNY"
      },
      {
        "title": "Deeper Love",
        "spotifyId": "7n2subz5J0refy5dZG1Rpg"
      },
      {
        "title": "Rock the Party",
        "spotifyId": "7JqKkV9l6J9TVSB1PX9PR2"
      }
    ]
  },
  "valentino-khan": {
    "genres": [],
    "spotifyArtistId": "0deIjoDjl9g9Zpw0sCIOHh",
    "tracks": [
      {
        "title": "Deep Down Low",
        "spotifyId": "48zgbsLhb3MirBgXt44nlH"
      },
      {
        "title": "Pump",
        "spotifyId": "0N98QCESfFA46B7a6TTZKq"
      }
    ]
  },
  "armin-van-buuren": {
    "genres": [],
    "spotifyArtistId": "0SfsnGyD8FpIN4U4WCkBZ5",
    "tracks": [
      {
        "title": "This Is What It Feels Like",
        "spotifyId": "5GjnIpUlLGEIYk052ISOw9"
      },
      {
        "title": "In and Out of Love",
        "spotifyId": "1FzbOPWCZiNxnLjAhY1jAR"
      },
      {
        "title": "Blah Blah Blah",
        "spotifyId": "1moFkZDqcjQNeXtyoanLHv"
      },
      {
        "title": "Communication",
        "spotifyId": "3Xoqg8LNJaGYvnpdsIYmOh"
      }
    ]
  },
  "above-and-beyond": {
    "genres": [],
    "spotifyArtistId": "10gzBoINW3cLJfZUka8Zoe",
    "tracks": [
      {
        "title": "Sun & Moon",
        "spotifyId": "4rfhAoZjGwraqwX1w47uij"
      },
      {
        "title": "We're All We Need",
        "spotifyId": "7jji8nfxJ84AJkUSpgruPL"
      },
      {
        "title": "Thing Called Love",
        "spotifyId": "0YuDHcx0WM1tGOyidHMwnz"
      }
    ]
  },
  "paul-van-dyk": {
    "genres": [],
    "spotifyArtistId": "7wU1naftD3lNq7rNsiDvOR",
    "tracks": [
      {
        "title": "For an Angel",
        "spotifyId": "5JcZHbUi60uykbQNXPLoCG"
      },
      {
        "title": "We Are Alive",
        "spotifyId": "7fRjxQ1g7A8WbNR6y1wuDZ"
      },
      {
        "title": "Nothing but You",
        "spotifyId": "5qwtQRNEhvzSEX4hrdDmRT"
      }
    ]
  },
  "ferry-corsten": {
    "genres": [],
    "spotifyArtistId": "2ohlvFf9PBsDELdRstPtlP",
    "tracks": [
      {
        "title": "Punk",
        "spotifyId": "74BSVo5XxxlOOWKstr8doF"
      },
      {
        "title": "Beautiful",
        "spotifyId": "4oxApW5sPwFiEQTkkjdmSj"
      },
      {
        "title": "Gouryella",
        "spotifyId": "6xl5vg5rhmbGI7kNML1IP4"
      }
    ]
  },
  "gareth-emery": {
    "genres": [],
    "spotifyArtistId": "0hprEC0nsWuQPSHag1O2Vi",
    "tracks": [
      {
        "title": "Concrete Angel",
        "spotifyId": "2zM1zEjv2JX1qTmSDeB8IL"
      },
      {
        "title": "Sanctuary",
        "spotifyId": "1ZB4LAVchsgiDOdR3yzMBz"
      },
      {
        "title": "Saving Light",
        "spotifyId": "7ckofk3m63RHNs9wiIl5LT"
      }
    ]
  },
  "atb": {
    "genres": [],
    "spotifyArtistId": "7jZM5w05mGhw6wTB1okhD9",
    "tracks": [
      {
        "title": "9 PM (Till I Come)",
        "spotifyId": "1CgbwsrNDlFrRuk2ebQ7zr"
      },
      {
        "title": "Ecstasy",
        "spotifyId": "2E09FnAzgoLEw8RzEJEEy9"
      },
      {
        "title": "Your Love (9PM)",
        "spotifyId": "5YaskwnGDZFDRipaqzbwQx"
      }
    ]
  },
  "charlotte-de-witte": {
    "genres": [],
    "spotifyArtistId": "1lJhME1ZpzsEa5M0wW6Mso",
    "tracks": [
      {
        "title": "Doppler",
        "spotifyId": "7J2ZnqSaDNijHboyFFkwpV"
      },
      {
        "title": "Formula",
        "spotifyId": "2r026RG46AioE6ze45oOd9"
      },
      {
        "title": "Sgadi Li Mi",
        "spotifyId": "7yjOcwS2yfuxJPYuzSAPVL"
      }
    ]
  },
  "amelie-lens": {
    "genres": [],
    "spotifyArtistId": "5Ho1vKl1Uz8bJlk4vbmvmf",
    "tracks": [
      {
        "title": "Higher",
        "spotifyId": "2lAC83w4MoLCgzq8G5RFPF"
      },
      {
        "title": "In My Mind",
        "spotifyId": "5UAtcDuXrfjU2jUtnEtYMZ"
      },
      {
        "title": "Contradiction",
        "spotifyId": "4nJXpGpkh59e4wLGgg8LI7"
      }
    ]
  },
  "adam-beyer": {
    "genres": [],
    "spotifyArtistId": "1btv9qmIpbp7q1ixCYNdHu",
    "tracks": [
      {
        "title": "Your Mind",
        "spotifyId": "2HC3zCi2hZffYhY7UBKBWa"
      },
      {
        "title": "Teach Me",
        "spotifyId": "1xaX6LJFXwSJkmEBW5xrZj"
      },
      {
        "title": "Space Date",
        "spotifyId": "6Z7g4cGUd0qpAdaY1jadz4"
      }
    ]
  },
  "carl-cox": {
    "genres": [],
    "spotifyArtistId": "19SmlbABtI4bXz864MLqOS",
    "tracks": [
      {
        "title": "I Want You (Forever)",
        "spotifyId": "6A2fGSY2uZcidWpNosshqc"
      },
      {
        "title": "Time for House Music",
        "spotifyId": "2TQYGgXdTf1Ne7cTbPKNT2"
      },
      {
        "title": "Phuture 2000",
        "spotifyId": "58aSEVveLPGAGoyzYNgUHt"
      }
    ]
  },
  "nina-kraviz": {
    "genres": [],
    "spotifyArtistId": "1oZmFNkGAT93yD1xX4vTRE",
    "tracks": [
      {
        "title": "Ghetto Kraviz",
        "spotifyId": "1vYUnLz9DfpJCnGB77UFFJ"
      },
      {
        "title": "Skyscrapers",
        "spotifyId": "2g95XDCx4GqcaJPv7TTk8C"
      }
    ]
  },
  "maceo-plex": {
    "genres": [],
    "spotifyArtistId": "3TXQ1ddouwQAI78hV4hXDj",
    "tracks": [
      {
        "title": "Solar Detroit",
        "spotifyId": "5F1832Fe7DXjtqHCHWWvtm"
      },
      {
        "title": "Mutant Disco",
        "spotifyId": "6NNx8nJJOsxxLVWPlh41S5"
      },
      {
        "title": "Conjure Superstar",
        "spotifyId": "5pYsZ4LY6LU4wEEDUGmsaB"
      }
    ]
  },
  "infected-mushroom": {
    "genres": [],
    "spotifyArtistId": "6S2tas4z6DyIklBajDqJxI",
    "tracks": [
      {
        "title": "Becoming Insane",
        "spotifyId": "4zh13oEiKl6W8qn9zsdQrp"
      },
      {
        "title": "The Pretender",
        "spotifyId": "4Q4V4NP8bvvJFBGFO3I9pM"
      },
      {
        "title": "Vicious Delicious",
        "spotifyId": "5NmapOMB0Z2Ce8sum21w1R"
      }
    ]
  },
  "vini-vici": {
    "genres": [],
    "spotifyArtistId": "29zsVzEH33dD5QqxeL8dvy",
    "tracks": [
      {
        "title": "The Tribe",
        "spotifyId": "3nwUX7DkMuGPcuHrOXN5VM"
      },
      {
        "title": "Great Spirit",
        "spotifyId": "3Nku6gLNqnwUuq8GLkqyhW"
      },
      {
        "title": "Universe Inside Me",
        "spotifyId": "3rTDI5zFvAWhcDW77ePuxp"
      }
    ]
  },
  "astrix": {
    "genres": [],
    "spotifyArtistId": "3dUltShd2gJQc98Kc7Syit",
    "tracks": [
      {
        "title": "Deep Jungle Walk",
        "spotifyId": "5gXKDmafOQ8i4lYr62wxTk"
      },
      {
        "title": "He.art",
        "spotifyId": "0IQ2lKaun7QeB4ixCbJoIb"
      },
      {
        "title": "Type 5",
        "spotifyId": "7hetvH14xUBhwEGJu6NujZ"
      }
    ]
  },
  "the-chemical-brothers": {
    "genres": [],
    "spotifyArtistId": "1GhPHrq36VKCY3ucVaZCfo",
    "tracks": [
      {
        "title": "Block Rockin' Beats",
        "spotifyId": "1FNvrp5K02oThumS6gllzp"
      },
      {
        "title": "Hey Boy Hey Girl",
        "spotifyId": "7kXmJwrZGIhDaLT9sNo3ut"
      },
      {
        "title": "Galvanize",
        "spotifyId": "4bz7uB4edifWKJXSDxwHcs"
      },
      {
        "title": "Go",
        "spotifyId": "2Xhd1kYKj2aee7JR3nIlRe"
      }
    ]
  },
  "the-prodigy": {
    "genres": [],
    "spotifyArtistId": "4k1ELeJKT1ISyDv8JivPpB",
    "tracks": [
      {
        "title": "Firestarter",
        "spotifyId": "1auX4gkGe7hbrOH0BXdpV4"
      },
      {
        "title": "Breathe",
        "spotifyId": "4ZtqsOdBbS6GoedzzRGSo9"
      },
      {
        "title": "Smack My Bitch Up",
        "spotifyId": "2iwGE4y7yF8qzKc5WZ2Z8R"
      },
      {
        "title": "Omen",
        "spotifyId": "2fplVRbbr1cBG7K5xt1hTE"
      }
    ]
  },
  "fatboy-slim": {
    "genres": [],
    "spotifyArtistId": "4Y7tXHSEejGu1vQ9bwDdXW",
    "tracks": [
      {
        "title": "Praise You",
        "spotifyId": "3yGy1JYz3zQKlxSgjgpQqX"
      },
      {
        "title": "The Rockafeller Skank",
        "spotifyId": "7mCQK9YB25WZw1saUjfL4e"
      },
      {
        "title": "Right Here, Right Now",
        "spotifyId": "3Pb9QabepyR9e9D8NqorPH"
      }
    ]
  },
  "pendulum": {
    "genres": [],
    "spotifyArtistId": "7MqnCTCAX6SsIYYdJCQj9B",
    "tracks": [
      {
        "title": "Watercolour",
        "spotifyId": "5ami95W9OOWQPwrBb5tud5"
      },
      {
        "title": "Propane Nightmares",
        "spotifyId": "6tC2iHfUlzB2W4ntXXL2BH"
      },
      {
        "title": "The Island",
        "spotifyId": "1Thv8uCYzyOFC7PME9J936"
      },
      {
        "title": "Witchcraft",
        "spotifyId": "4Y2glvLjQGOb4dXnwm1hQf"
      }
    ]
  },
  "netsky": {
    "genres": [],
    "spotifyArtistId": "5TgQ66WuWkoQ2xYxaSTnVP",
    "tracks": [
      {
        "title": "Rio",
        "spotifyId": "5IfSQQzGijWKd7dbkbqHuN"
      },
      {
        "title": "Come Alive",
        "spotifyId": "1nu3xsANYakfYv242EAnVm"
      },
      {
        "title": "Work It Out",
        "spotifyId": "7L2H9LWWKBLhITaUZLFMdy"
      }
    ]
  },
  "sub-focus": {
    "genres": [],
    "spotifyArtistId": "0QaSiI5TLA4N7mcsdxShDO",
    "tracks": [
      {
        "title": "Turn Back Time",
        "spotifyId": "0qCgbIJOBYM5sGAVXUuPI6"
      },
      {
        "title": "Tidal Wave",
        "spotifyId": "3NKLPcvDM0pefpLNcmui2W"
      },
      {
        "title": "Could This Be Real",
        "spotifyId": "6kKkZOTKmJOWMD1SjXQ2Yc"
      }
    ]
  },
  "chase-and-status": {
    "genres": [],
    "spotifyArtistId": "3jNkaOXasoc7RsxdchvEVq",
    "tracks": [
      {
        "title": "Blind Faith",
        "spotifyId": "04OxTCLGgDKfO0MMA2lcxv"
      },
      {
        "title": "End Credits",
        "spotifyId": "64I0O6ZipYryKte1cHA2EY"
      },
      {
        "title": "Baddadan",
        "spotifyId": "2ZWmmrWUgDBcPSLihBMvhg"
      }
    ]
  },
  "wilkinson": {
    "genres": [],
    "spotifyArtistId": "6m8itYST9ADjBIYevXSb1r",
    "tracks": [
      {
        "title": "Afterglow",
        "spotifyId": "6LW3Z1GqbL78TIjfDyg4zp"
      },
      {
        "title": "Sweet Lies",
        "spotifyId": "6YNQNR6E9AeCzWi2JYi1n2"
      }
    ]
  },
  "andy-c": {
    "genres": [],
    "spotifyArtistId": "75HK7rgkmDMTnWwwmcN53N",
    "tracks": [
      {
        "title": "Heartbeat Loud",
        "spotifyId": "5PuJ00qKGWqbGeeWbt8WJb"
      },
      {
        "title": "What Bass",
        "spotifyId": "1CFxmzRPmVEL8Q1PLpewOV"
      }
    ]
  },
  "goldie": {
    "genres": [],
    "spotifyArtistId": "2SYqJ3uDLLXZNyZdLKBy4M",
    "tracks": [
      {
        "title": "Inner City Life",
        "spotifyId": "4TOIdyhxz1xgAlrrz2HHhT"
      },
      {
        "title": "Timeless",
        "spotifyId": "7AvrJG89s3bVBWNqaLa8Le"
      }
    ]
  },
  "roni-size": {
    "genres": [],
    "spotifyArtistId": "5UjqeSp9dX6Nrge7WdDukr",
    "tracks": [
      {
        "title": "Brown Paper Bag",
        "spotifyId": "3ZQs8RHO3lPZoUwpavPENL"
      },
      {
        "title": "Watching Windows",
        "spotifyId": "07ULOjpYwq8cyuEQzAqQbF"
      }
    ]
  },
  "nia-archives": {
    "genres": [],
    "spotifyArtistId": "7BMR0fwtEvzGtK4rNGdoiQ",
    "tracks": [
      {
        "title": "Baianá",
        "spotifyId": "7B0gxo0jQCy5Lk93RIODAC"
      },
      {
        "title": "So Tell Me...",
        "spotifyId": "3FwfEBrr6MUPFqQFGY2ZKw"
      },
      {
        "title": "Off Wiv Ya Headz",
        "spotifyId": "29LpCEcWnk9lFfzR2o3YVW"
      }
    ]
  },
  "burial": {
    "genres": [],
    "spotifyArtistId": "0uCCBpmg6MrPb1KY2msceF",
    "tracks": [
      {
        "title": "Archangel",
        "spotifyId": "55gnBQAhU5rGzLsXTAx2MM"
      },
      {
        "title": "Untrue",
        "spotifyId": "0YPg9B9SUzo528Pqhnlt62"
      },
      {
        "title": "Ghost Hardware",
        "spotifyId": "5m1VR5YlkswXMoHSmGWFqa"
      }
    ]
  },
  "overmono": {
    "genres": [],
    "spotifyArtistId": "01PnN11ovfen6xUOHfNpn3",
    "tracks": [
      {
        "title": "So U Kno",
        "spotifyId": "1YGxSgWIWqxKuLLocPVxhC"
      },
      {
        "title": "Is U",
        "spotifyId": "14gYIWhaZ3kKQiwr7kI4JQ"
      },
      {
        "title": "Gunk",
        "spotifyId": "4Nv1liSp522fuF1AGu6Yxs"
      }
    ]
  },
  "interplanetary-criminal": {
    "genres": [],
    "spotifyArtistId": "6uJ51uV5rYzu1MJkC4CceI",
    "tracks": [
      {
        "title": "B.O.T.A. (Baddest of Them All)",
        "spotifyId": "39JofJHEtg8I4fSyo7Imft"
      },
      {
        "title": "Tell Me",
        "spotifyId": "4hZ17ryjXAq6OjpoH3CSke"
      }
    ]
  },
  "skrillex": {
    "genres": [],
    "spotifyArtistId": "5he5w2lnU9x7JFhnwcekXX",
    "tracks": [
      {
        "title": "Scary Monsters and Nice Sprites",
        "spotifyId": "4rwpZEcnalkuhPyGkEdhu0"
      },
      {
        "title": "Bangarang",
        "spotifyId": "6VRhkROS2SZHGlp0pxndbJ"
      },
      {
        "title": "First of the Year (Equinox)",
        "spotifyId": "5i7fZq3chLyCHo3VeB6goD"
      },
      {
        "title": "Rumble",
        "spotifyId": "74fmYjFwt9CqEFAh8ybeBD"
      }
    ]
  },
  "excision": {
    "genres": [],
    "spotifyArtistId": "5FKchcZpQOkqFvXBj1aCvb",
    "tracks": [
      {
        "title": "The Paradox",
        "spotifyId": "77i4LJA3KRQYxXs2Y3tQhs"
      },
      {
        "title": "Throwin' Elbows",
        "spotifyId": "5Z9gjSD3mglkexfM8QbGHo"
      },
      {
        "title": "Robo Kitty",
        "spotifyId": "0add6VGNTx9QkCFoJMAZ13"
      }
    ]
  },
  "subtronics": {
    "genres": [],
    "spotifyArtistId": "3NJ94iuAmmMjbszODYT6pO",
    "tracks": [
      {
        "title": "Griztronics",
        "spotifyId": "6OTClxme7EYRZGO6An3SMc"
      },
      {
        "title": "Scott Pilgrim",
        "spotifyId": "1LVXkhEMVj4jUJKYMm3N77"
      },
      {
        "title": "Antifragile",
        "spotifyId": "4lZeuyDBKb1eRso3a4ueAY"
      }
    ]
  },
  "zomboy": {
    "genres": [],
    "spotifyArtistId": "0ycHhPwPvoaO4VGzmMnXGq",
    "tracks": [
      {
        "title": "Nuclear (Hands Up)",
        "spotifyId": "32AV76N8GhpnJ74VoYfDGk"
      },
      {
        "title": "Terror Squad",
        "spotifyId": "3iua7Qv6SauKb6AIRErIDE"
      }
    ]
  },
  "flux-pavilion": {
    "genres": [],
    "spotifyArtistId": "7muzHifhMdnfN1xncRLOqk",
    "tracks": [
      {
        "title": "Bass Cannon",
        "spotifyId": "5tMgzjTvBno3TE6Yo1zUtv"
      },
      {
        "title": "I Can't Stop",
        "spotifyId": "5WSL7UTa38jMWoBzObD4BD"
      }
    ]
  },
  "knife-party": {
    "genres": [],
    "spotifyArtistId": "2DuJi13MWHjRHrqRUwk8vH",
    "tracks": [
      {
        "title": "Internet Friends",
        "spotifyId": "5qFL2uwfnGU8FccwLMgPNQ"
      },
      {
        "title": "Bonfire",
        "spotifyId": "0QIYINh2AwmOmdu8CRYvlw"
      },
      {
        "title": "Centipede",
        "spotifyId": "0u2AIKDVafHwCFQ9LDnqxH"
      }
    ]
  },
  "zeds-dead": {
    "genres": [],
    "spotifyArtistId": "67qogtRNI0GjUr8PlaG6Zh",
    "tracks": [
      {
        "title": "Collapse",
        "spotifyId": "5adUFm4TGGUMBzmbWsIqXf"
      },
      {
        "title": "Hadouken",
        "spotifyId": "6kuSR6XoH8LrNIIPsR60xF"
      },
      {
        "title": "Eyes on Fire (Remix)",
        "spotifyId": "3Oiauiojgokw9vWQvFmEoI"
      }
    ]
  },
  "nero": {
    "genres": [],
    "spotifyArtistId": "4uRYpUQZrNrY5t8tAv3XrD",
    "tracks": [
      {
        "title": "Promises",
        "spotifyId": "7569Hbv0FUS7vjkdGvdgeZ"
      },
      {
        "title": "Me & You",
        "spotifyId": "0xIof5gmHjFY0t1eX7angP"
      },
      {
        "title": "Crush on You",
        "spotifyId": "6NJNZKFys2ypAG7L0XKaeT"
      }
    ]
  },
  "illenium": {
    "genres": [],
    "spotifyArtistId": "45eNHdiiabvmbp4erw26rg",
    "tracks": [
      {
        "title": "Good Things Fall Apart",
        "spotifyId": "3LxG9HkMMFP0MZuiw3O2rF"
      },
      {
        "title": "Take You Down",
        "spotifyId": "6f1oG9hTx3NETgV6q4rkw5"
      },
      {
        "title": "Crawl Outta Love",
        "spotifyId": "49o6YjBAnjwPKLcXwIH53Z"
      },
      {
        "title": "Beautiful Creatures",
        "spotifyId": "2NmuyZa8Co3mMesQQUkXNO"
      }
    ]
  },
  "seven-lions": {
    "genres": [],
    "spotifyArtistId": "6fcTRFpz0yH79qSKfof7lp",
    "tracks": [
      {
        "title": "Strangers",
        "spotifyId": "2U0pVx4m1Kdm1Gsjjm6iq8"
      },
      {
        "title": "Rush Over Me",
        "spotifyId": "3JAuRdjjPOzKMvcT24Uxiq"
      },
      {
        "title": "Days to Come",
        "spotifyId": "1FRFgyPNuqfXIRYlCJ1kwR"
      }
    ]
  },
  "said-the-sky": {
    "genres": [],
    "spotifyArtistId": "4LZ4De2MoO3lP6QaNCfvcu",
    "tracks": [
      {
        "title": "Faith",
        "spotifyId": "2RFUtPwlsXEL1QLFQWAJjd"
      },
      {
        "title": "Walk Me Home",
        "spotifyId": "5fWRLdgfMlbKDncAhdN9zI"
      }
    ]
  },
  "flume": {
    "genres": [],
    "spotifyArtistId": "6nxWCVXbOlEVRexSbLsTer",
    "tracks": [
      {
        "title": "Never Be Like You",
        "spotifyId": "2ZYz5aPLnEkGR1DfWGZGn6"
      },
      {
        "title": "Say It",
        "spotifyId": "7sBQgOhEfJzvAnIw8TpcNt"
      },
      {
        "title": "Rushing Back",
        "spotifyId": "4uyYsLMnxzzIB6LE81g4OF"
      },
      {
        "title": "Holdin On",
        "spotifyId": "0IW97aCIWMRHc16XLnCCC5"
      }
    ]
  },
  "odesza": {
    "genres": [],
    "spotifyArtistId": "21mKp7DqtSNHhCAU2ugvUw",
    "tracks": [
      {
        "title": "Say My Name",
        "spotifyId": "1LeItUMezKA1HdCHxYICed"
      },
      {
        "title": "Sun Models",
        "spotifyId": "7jZHUhAmW5oq1cq6s8IxmK"
      },
      {
        "title": "A Moment Apart",
        "spotifyId": "59wlTaYOL5tDUgXnbBQ3my"
      },
      {
        "title": "Line of Sight",
        "spotifyId": "2WWfjbHALIb3e7FMcj9mr4"
      }
    ]
  },
  "porter-robinson": {
    "genres": [],
    "spotifyArtistId": "3dz0NnIZhtKKeXZxLOxCam",
    "tracks": [
      {
        "title": "Language",
        "spotifyId": "3NRDLYyqIXja0UElvdzjkB"
      },
      {
        "title": "Shelter",
        "spotifyId": "2ewEh7LuvToYyGHq7yT8N1"
      },
      {
        "title": "Sad Machine",
        "spotifyId": "1JY6B9ILvmRla2IKKRZvnH"
      },
      {
        "title": "Look at the Sky",
        "spotifyId": "7LMajLn4v2ZWmLcfE1a7DY"
      }
    ]
  },
  "madeon": {
    "genres": [],
    "spotifyArtistId": "4pb4rqWSoGUgxm63xmJ8xc",
    "tracks": [
      {
        "title": "Shelter",
        "spotifyId": "2ewEh7LuvToYyGHq7yT8N1"
      },
      {
        "title": "All My Friends",
        "spotifyId": "3ArdPRbscsYB2uI70AzpuG"
      },
      {
        "title": "Pop Culture",
        "spotifyId": "43GuU2ue9KOqVecgBKZ6be"
      }
    ]
  },
  "marshmello": {
    "genres": [],
    "spotifyArtistId": "64KEffDW9EtZ1y2vBYgq8T",
    "tracks": [
      {
        "title": "Alone",
        "spotifyId": "3MEYFivt6bilQ9q9mFWZ4g"
      },
      {
        "title": "Silence",
        "spotifyId": "7vGuf3Y35N4wmASOKLUVVU"
      },
      {
        "title": "Happier",
        "spotifyId": "7BqHUALzNBTanL6OvsqmC1"
      },
      {
        "title": "Friends",
        "spotifyId": "1wIyr1y5wiWqo7nqbxHpWt"
      }
    ]
  },
  "gryffin": {
    "genres": [],
    "spotifyArtistId": "2ZRQcIgzPCVaT9XKhXZIzh",
    "tracks": [
      {
        "title": "Tie Me Down",
        "spotifyId": "2zh01m4PiHaZz4BAm0NRxs"
      },
      {
        "title": "OMG",
        "spotifyId": "1a0M7E4aQgkMkuwpjnX9Nr"
      }
    ]
  },
  "san-holo": {
    "genres": [],
    "spotifyArtistId": "0jNDKefhfSbLR9sFvcPLHo",
    "tracks": [
      {
        "title": "Light",
        "spotifyId": "6jq6rcOikCZAmjliAgAmfT"
      },
      {
        "title": "We Rise",
        "spotifyId": "0P4OPRMHGNIa8TxNvdNUy5"
      }
    ]
  },
  "louis-the-child": {
    "genres": [],
    "spotifyArtistId": "7wg1qvie3KqDNQbAkTdbX0",
    "tracks": [
      {
        "title": "It's Strange",
        "spotifyId": "2Th9BGKvfZG8bKQSACitwG"
      },
      {
        "title": "Better Not",
        "spotifyId": "7n1940b6kHcaEewFSZXnXa"
      }
    ]
  },
  "rezz": {
    "genres": [],
    "spotifyArtistId": "4aKdmOXdUKX07HVd3sGgzw",
    "tracks": [
      {
        "title": "Edge",
        "spotifyId": "5pusGtgNOBo2PnRMWuz8L2"
      },
      {
        "title": "Falling",
        "spotifyId": "2jy15HYKNtWQ0STN9ZOw8v"
      },
      {
        "title": "Hex",
        "spotifyId": "3AlPT1xviSENm5hxtIrAzv"
      }
    ]
  },
  "griz": {
    "genres": [],
    "spotifyArtistId": "25oLRSUjJk4YHNUsQXk7Ut",
    "tracks": [
      {
        "title": "Smoke",
        "spotifyId": "4breLybOC3ue7UOkD8uTyZ"
      },
      {
        "title": "The Anthem",
        "spotifyId": "46xQ9PYlIVc3EMRezS6Owr"
      }
    ]
  },
  "pretty-lights": {
    "genres": [],
    "spotifyArtistId": "4iVhFmG8YCCEHANGeUUS9q",
    "tracks": [
      {
        "title": "Finally Moving",
        "spotifyId": "3WS7spXVlbeC5kjePmHMQW"
      },
      {
        "title": "Lost and Found",
        "spotifyId": "69d67l28GKygFwW4QbyfDR"
      }
    ]
  },
  "big-gigantic": {
    "genres": [],
    "spotifyArtistId": "7o7mC95EDbJKTcPAAs8C3r",
    "tracks": [
      {
        "title": "The Little Things",
        "spotifyId": "6bC7spF0E7vVSFVN7DQ7dD"
      },
      {
        "title": "C'mon",
        "spotifyId": "7m2gpufonpin9HmrdUqg4b"
      }
    ]
  },
  "rl-grime": {
    "genres": [],
    "spotifyArtistId": "5eIbEEQnDM8yuDVB0bimSP",
    "tracks": [
      {
        "title": "Core",
        "spotifyId": "097ivRfD5gBHjqhwEMifOT"
      },
      {
        "title": "UCLA",
        "spotifyId": "0r8RKKIc4C8G6J9HAHzpaR"
      },
      {
        "title": "Tell Me",
        "spotifyId": "5HmOTLgXEBP4cHFVeYAlhv"
      }
    ]
  },
  "baauer": {
    "genres": [],
    "spotifyArtistId": "25fqWEebq6PoiGQIHIrdtv",
    "tracks": [
      {
        "title": "Harlem Shake",
        "spotifyId": "01XFgRZfZI7oBagNf1Loml"
      },
      {
        "title": "Day Ones",
        "spotifyId": "1ThGBiSfwyJeWCTqTcTyXL"
      }
    ]
  },
  "what-so-not": {
    "genres": [],
    "spotifyArtistId": "4AA8eXtzqh5ykxtafLaPOi",
    "tracks": [
      {
        "title": "High You Are",
        "spotifyId": "4YIoQqE50AdyG4BQafCi3u"
      },
      {
        "title": "Gemini",
        "spotifyId": "6sjtHq6EueMR7otphregK5"
      }
    ]
  },
  "showtek": {
    "genres": [],
    "spotifyArtistId": "3gk0OYeLFWYupGFRHqLSR7",
    "tracks": [
      {
        "title": "Booyah",
        "spotifyId": "55SPQmrp0XawJSbBtPelaA"
      },
      {
        "title": "Bad",
        "spotifyId": "06dT0EYXrhRQV1MsvWhNGv"
      },
      {
        "title": "Cannonball (Earthquake)",
        "spotifyId": "6gNyDzvD0lwB0WY2llTkFc"
      }
    ]
  },
  "headhunterz": {
    "genres": [],
    "spotifyArtistId": "6C0KWmCdqrLU2LzzWBPbOy",
    "tracks": [
      {
        "title": "Dragonborn",
        "spotifyId": "2ODL67XP6x6PYflx4RkXxs"
      },
      {
        "title": "Psychedelic",
        "spotifyId": "2vmg0D8hGxVbQSeszkRRmq"
      },
      {
        "title": "The Power of the Mind",
        "spotifyId": "5sdQto0Jziq716njJr31XR"
      }
    ]
  },
  "da-tweekaz": {
    "genres": [],
    "spotifyArtistId": "6UOk7DmvqlzWmo6gjhZvn6",
    "tracks": [
      {
        "title": "Break the Spell",
        "spotifyId": "0wCwnV6lMlg7WXFKLkKz9X"
      },
      {
        "title": "Tikbalang",
        "spotifyId": "19MTjzkV7hZTUDXywlJbVL"
      },
      {
        "title": "Frozen",
        "spotifyId": "5rEwVrcWQy2hn7bV78rwJC"
      }
    ]
  },
  "brennan-heart": {
    "genres": [],
    "spotifyArtistId": "5QySqc6yAFDx9m7fedFZmC",
    "tracks": [
      {
        "title": "Imaginary",
        "spotifyId": "2kkh8Z3tlBDY8jhT4bWrC6"
      },
      {
        "title": "Lose My Mind",
        "spotifyId": "1FKUPb2HdRzrwpbhF5gqsk"
      }
    ]
  },
  "wildstylez": {
    "genres": [],
    "spotifyArtistId": "0wr85NuJuAYZsRzP1lJgiV",
    "tracks": [
      {
        "title": "Year of Summer",
        "spotifyId": "3iKcDwqwMf6O547uQcyjaO"
      },
      {
        "title": "Lies or Truth",
        "spotifyId": "7lQJrNMwkgrK6Ji4yvFApt"
      }
    ]
  },
  "angerfist": {
    "genres": [],
    "spotifyArtistId": "4sQNUQjOYj9rV2sdfJ8laS",
    "tracks": [
      {
        "title": "Raise & Revolt",
        "spotifyId": "2FgXDkdyeWhhqIIM7THQle"
      },
      {
        "title": "Incoming!",
        "spotifyId": "4XiGPZPtOG6r6jT6rB0XJR"
      }
    ]
  },
  "darren-styles": {
    "genres": [],
    "spotifyArtistId": "2gZzTzeACSwFqkMroVxmnm",
    "tracks": [
      {
        "title": "Save Me",
        "spotifyId": "7AnjesDPOC4EUmUL6TjFkR"
      },
      {
        "title": "Us Against the World",
        "spotifyId": "0L0DM33NAe6PjQ1BB4cEjJ"
      }
    ]
  },
  "gammer": {
    "genres": [],
    "spotifyArtistId": "5nd7jnne7zbsV2J5jBKNOY",
    "tracks": [
      {
        "title": "The Drop",
        "spotifyId": "2sEeRKHVONJGERCwKCW2ix"
      },
      {
        "title": "Hi5",
        "spotifyId": "0vW1sSMv0GxRdlS3NDrxPS"
      }
    ]
  },
  "s3rl": {
    "genres": [],
    "spotifyArtistId": "11aa081aKYUzmeFm0yHdT2",
    "tracks": [
      {
        "title": "Pretty Rave Girl",
        "spotifyId": "3G1SVODcssMmS5YM5G3tun"
      },
      {
        "title": "MTC",
        "spotifyId": "56nLHj9HJr3xpbLarnr0l4"
      }
    ]
  },
  "major-lazer": {
    "genres": [],
    "spotifyArtistId": "738wLrAtLtCtFOLvQBXOXp",
    "tracks": [
      {
        "title": "Lean On",
        "spotifyId": "01aTsQoKoeXofSTvKuunzv"
      },
      {
        "title": "Light It Up",
        "spotifyId": "1qFSPn37zEeCyRiVpkW9dt"
      },
      {
        "title": "Cold Water",
        "spotifyId": "7zsXy7vlHdItvUSH8EwQss"
      },
      {
        "title": "Run Up",
        "spotifyId": "4Ezpn0nl7RC8lDXQSuC72j"
      }
    ]
  },
  "diplo": {
    "genres": [],
    "spotifyArtistId": "5fMUXHkw8R8eOP2RNVYEZX",
    "tracks": [
      {
        "title": "Revolution",
        "spotifyId": "7aaeZpSr54XQKSwMYO5JeH"
      },
      {
        "title": "Be Right There",
        "spotifyId": "2egKQvoHiCJyHXn8lRlsrl"
      },
      {
        "title": "Get It Right",
        "spotifyId": "0Sxmsu0FjqqxtasyjIjbkh"
      }
    ]
  },
  "dj-snake": {
    "genres": [],
    "spotifyArtistId": "540vIaP2JwjQb9dm3aArA4",
    "tracks": [
      {
        "title": "Turn Down for What",
        "spotifyId": "67awxiNHNyjMXhVgsHuIrs"
      },
      {
        "title": "Lean On",
        "spotifyId": "01aTsQoKoeXofSTvKuunzv"
      },
      {
        "title": "Taki Taki",
        "spotifyId": "0KoiMHhqKLoL4xM54rcWYY"
      },
      {
        "title": "Let Me Love You",
        "spotifyId": "0lYBSQXN6rCTvUZvg9S0lU"
      }
    ]
  },
  "dillon-francis": {
    "genres": [],
    "spotifyArtistId": "5R3Hr2cnCCjt220Jmt2xLf",
    "tracks": [
      {
        "title": "Get Low",
        "spotifyId": "3oZoXyU0SkDldgS7AcN4y4"
      },
      {
        "title": "Need You",
        "spotifyId": "20UdW4qyeOmKa9YaOcv9WX"
      },
      {
        "title": "Hey",
        "spotifyId": "4A21XZz1IdfrzY9urwXJM0"
      }
    ]
  },
  "kordhell": {
    "genres": [],
    "spotifyArtistId": "2W6WP4pHQTFlbr2z9S4n54",
    "tracks": [
      {
        "title": "Murder in My Mind",
        "spotifyId": "6qyS9qBy0mEk3qYaH8mPss"
      },
      {
        "title": "Lifestyle",
        "spotifyId": "5WNBGRcXWeoXrXJHrQqodi"
      }
    ]
  },
  "dvrst": {
    "genres": [],
    "spotifyArtistId": "0XFgyr4jwM0MGeZZW0VzA5",
    "tracks": [
      {
        "title": "Close Eyes",
        "spotifyId": "3CLSHJv5aUROAN2vfOyCOh"
      },
      {
        "title": "Phonky Town",
        "spotifyId": "3CLSHJv5aUROAN2vfOyCOh"
      }
    ]
  },
  "ghostface-playa": {
    "genres": [],
    "spotifyArtistId": "5xegBBY3vjR75woVR9kiy7",
    "tracks": [
      {
        "title": "Why Not",
        "spotifyId": "4oMyggIzClkOcCTvotFLkP"
      },
      {
        "title": "Stop Playing",
        "spotifyId": "1LaMTILNmivxzqujxB4dlh"
      }
    ]
  },
  "kabza-de-small": {
    "genres": [],
    "spotifyArtistId": "1bNjWBFWsAAzZSR59lRdpR",
    "tracks": [
      {
        "title": "Sponono",
        "spotifyId": "5VGoJV02KbfPGhS764PwoH"
      },
      {
        "title": "Asibe Happy",
        "spotifyId": "6F70m9aMK4PSJKBfp1H8DZ"
      }
    ]
  },
  "dj-maphorisa": {
    "genres": [],
    "spotifyArtistId": "0mMqD2uqwvCjFvlzo6ayGi",
    "tracks": [
      {
        "title": "Izolo",
        "spotifyId": "2lM7orFD058wiAiBixzffm"
      },
      {
        "title": "Banyana",
        "spotifyId": "6bgandzIQ55wqEYRlpSraS"
      }
    ]
  },
  "uncle-waffles": {
    "genres": [],
    "spotifyArtistId": "68McnNC9twEtiynOAJRRgZ",
    "tracks": [
      {
        "title": "Tanzania",
        "spotifyId": "4qm0rzVQA3kqQ0yA7LkuFK"
      },
      {
        "title": "Yahyuppiyah",
        "spotifyId": "0c5uvxHB8Fhy9YmnO4KOHk"
      }
    ]
  },
  "the-midnight": {
    "genres": [],
    "spotifyArtistId": "2NFrAuh8RQdQoS7iYFbckw",
    "tracks": [
      {
        "title": "Sunset",
        "spotifyId": "6mB9A9YLbY4jxpKX5EYAnT"
      },
      {
        "title": "Days of Thunder",
        "spotifyId": "28uitw2AXQQIUHvSJW9qy6"
      },
      {
        "title": "Vampires",
        "spotifyId": "5lVsAfvY2ij8A2T6oYdAyt"
      }
    ]
  },
  "kavinsky": {
    "genres": [],
    "spotifyArtistId": "0UF7XLthtbSF2Eur7559oV",
    "tracks": [
      {
        "title": "Nightcall",
        "spotifyId": "0U0ldCRmgCqhVvD6ksG63j"
      },
      {
        "title": "Odd Look",
        "spotifyId": "3Q6mwJseOFYBJ10d5CXp4o"
      }
    ]
  },
  "carpenter-brut": {
    "genres": [],
    "spotifyArtistId": "1l2oLiukA9i5jEtIyNWIEP",
    "tracks": [
      {
        "title": "Turbo Killer",
        "spotifyId": "10qbHF920zH5K8C8IcE5AL"
      },
      {
        "title": "Le Perv",
        "spotifyId": "1coJ1H1FiEZG93naXkOsNF"
      }
    ]
  },
  "perturbator": {
    "genres": [],
    "spotifyArtistId": "244uLu9lkdw39BJwlul3k8",
    "tracks": [
      {
        "title": "Future Club",
        "spotifyId": "20ztml2STRF7Sq1UaBB6ox"
      },
      {
        "title": "Sentient",
        "spotifyId": "5jz2XYi3qJC3nN62FW1PUp"
      }
    ]
  },
  "gunship": {
    "genres": [],
    "spotifyArtistId": "3PALZKWkpwjRvBsRmhlVSS",
    "tracks": [
      {
        "title": "Tech Noir",
        "spotifyId": "5VKEsChbUowEF2BT0gJSGX"
      },
      {
        "title": "Dark All Day",
        "spotifyId": "4GBJomKlZNRnODfpL299pw"
      }
    ]
  },
  "green-velvet": {
    "genres": [],
    "spotifyArtistId": "3ABaec4jjl95VqmG1iD4k2",
    "tracks": [
      {
        "title": "La La Land",
        "spotifyId": "5hYSsLVQ6Isk6YZrnsBj4E"
      },
      {
        "title": "Flash",
        "spotifyId": "5o86zWm0MZAY9yu5TPWRbP"
      },
      {
        "title": "Bigger Than Prince",
        "spotifyId": "3PW35Q7BLZ4xoHgCRxUZ4f"
      }
    ]
  }
};
