/**
 * Generated by scripts/resolve-beatport.ts — safe to commit, do not edit by
 * hand. Maps a track key to the raw Beatport genre tag(s) for that release, so
 * the artist pages can show true per-song genres. Empty until the scraper runs;
 * the merge layer (artistsAtlas.ts) treats an empty map as "seed only".
 *
 * Key format: `${artistSlug}|${titleSlug}` using trackKey() from trackKey.ts so
 * the seed and the scraper agree on how a track is identified.
 *
 * Currently empty by choice: see scripts/resolve-beatport.ts — Beatport's
 * artist search surfaces recent/remix releases rather than an artist's iconic
 * tracks, so it can't reliably tag the curated seed's songs. The curated
 * per-song genres in artists.ts are the source until that's improved.
 */

export const BEATPORT_GENRES: Record<string, string[]> = {};
